### ISSUE TITLE
PIP (Picture-in-Picture) is broken

### ISSUE THREAD

**Issue by robloxianstudio123-1** [unknown81311/BetterMediaPlayer#12]
Discovered this today, I don't know if there is an duplicate bug report of the same one
So..
Update: [There is an duplicate report](https://github.com/unknown81311/BetterMediaPlayer/issues/5)

Expected Results: **PIP is supposed to work as normal**
Actual Results: Trying to go to PIP results into an **blank screen, stays on top** (Image provided)
![image](https://github.com/unknown81311/BetterMediaPlayer/assets/148556463/ff64d3b6-42a3-4462-b08e-287e70b55618)

Repro:
1. Send an video (Any video)
2. Play the video
3. Go to PIP (Picture-in-Picture)

I'll now have to wait until this bug gets fixed

**Comment by robloxianstudio123-1** [comment]
> Discovered this today, I don't know if there is an duplicate bug report of the same one So..
> 
> Expected Results: **PIP is supposed to work as normal** Actual Results: Trying to go to PIP results into an **blank screen, stays on top** (Image provided) ![image](https://user-images.githubusercontent.com/148556463/279670315-ff64d3b6-42a3-4462-b08e-287e70b55618.png)
> 
> Repro:
> 
> 1. Send an video (Any video)
> 2. Play the video
> 3. Go to PIP (Picture-in-Picture)
> 
> I'll now have to wait until this bug gets fixed

[Duplicate report of an closed issue](https://github.com/unknown81311/BetterMediaPlayer/issues/5)

**Comment by Enrico9431** [comment]
![image](https://github.com/unknown81311/BetterMediaPlayer/assets/85672311/2a3038bf-76a1-46f9-a69c-b5fdd44bab35)
Buttons broken as well

**Comment by doggybootsy** [comment]
fixed in latest pus
