### ISSUE TITLE
Buttons are broken

### ISSUE THREAD

**Issue by TheGreatTaz** [unknown81311/BetterMediaPlayer#13]
buttons added by extension are oversized and in some aspect ratios cover up/hide other important buttons
![Screenshot 2023-11-09 235827](https://github.com/unknown81311/BetterMediaPlayer/assets/89170620/b2154cfd-4934-4e21-836e-cc05387c2678)
![Screenshot 2023-11-09 235959](https://github.com/unknown81311/BetterMediaPlayer/assets/89170620/f5c1bfad-f7f8-4963-a0db-61236a383ec9)

**Comment by doggybootsy** [comment]
fixed in latest push
