### ISSUE TITLE
Doesnt work after Discord update

### ISSUE THREAD

**Issue by DimTheEnderman** [unknown81311/BetterMediaPlayer#18]
Just updated Discord and now the addon wont load
![Screenshot 2024-06-26 121310](https://github.com/unknown81311/BetterMediaPlayer/assets/169503763/2e834d12-2243-42c7-9032-e2e4dab9f5e6)

**Comment by doggybootsy** [comment]
Closing as this is a duplicate https://github.com/unknown81311/BetterMediaPlayer/issues/17
