### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by maxens-wlfr** [unknown81311/BetterMediaPlayer#9]
I get an error at startup saying the plugin can not be compiled

**Comment by jellejurre** [comment]
![image](https://user-images.githubusercontent.com/76777936/205446209-d05ebc4f-29be-4eaf-b1c2-37fc00d1bd1b.png)

**Comment by doggybootsy** [comment]
Should be fixed in the latest github commit

**Comment by unkn0wncvm1** [comment]
> ![image](https://user-images.githubusercontent.com/76777936/205446209-d05ebc4f-29be-4eaf-b1c2-37fc00d1bd1b.png)

Download the plugin from github, BetterDiscord's Website Doesnt Update often.
